FROM            eb-docker:base
MAINTAINER      zehye.01@gmail.com

ENV             BUILD_MODE              local
ENV             DJANGO_SETTINGS_MODULE  config.settings.${BUILD_MODE}

COPY            .   /srv/project

WORKDIR         /srv/project/app
CMD             python manage.py runserver 0:8000